# Taken from https://docs.docker.com/examples/running_ssh_service/

FROM karsten/ssh-base
MAINTAINER Karsten Ahnert <karsten.ahnert@gmx.de>

RUN sudo apt-get install -y openjdk-7-jre
ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64
